services:
  - type: web
    name: client-portal
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/employeeportal-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.java
      - key: MAVEN_HOME
        value: /opt/render/project/.maven